### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by LeXuanNguyen** [JamesBrill/react-speech-recognition#110]
This error is reported when I use the library on my project:

Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by amirzenoozi** [comment]
I have the same issue when I use in my `typescript` project

**Comment by JamesBrill** [comment]
Hi @LeXuanNguyen @amirzenoozi Check out [this](https://github.com/JamesBrill/react-speech-recognition#regeneratorruntime-is-not-defined). Let me know if that helps.

**Comment by amirzenoozi** [comment]
@JamesBrill I Check That Link and It's Work But Only In Chrome Browser and the other issue is we don't have `browserSupportsSpeechRecognition` in `useSpeechRecognition()` What Should I Do About This?

**Comment by JamesBrill** [comment]
@amirzenoozi Do you mean that after installing and importing `regenerator-runtime`, you still see `regeneratorRuntime is not defined` in browsers other than Chrome? Or do you mean that speech recognition functionality does not work outside of Chrome? The latter is largely true due to the limited support for the Web Speech API in many browsers (see [supported browsers](https://github.com/JamesBrill/react-speech-recognition#supported-browsers)). Your options are to either use [browserSupportsSpeechRecognition](https://github.com/JamesBrill/react-speech-recognition#detecting-browser-support-for-web-speech-api) to turn off your voice-driven feature on unsupported browsers, or to use a [polyfill](https://github.com/JamesBrill/react-speech-recognition#why-you-should-use-a-polyfill-with-this-library).

Regarding `browserSupportsSpeechRecognition`, perhaps you can share some code or a link to your repo in a separate GitHub issue so I can better understand the problem. This boolean property is returned as state from the `useSpeechRecognition` hook and should reflect the support for speech recognition in the browser.

**Comment by rafaelsouzagomes** [comment]
i had this issue in all of the browsers.
app.js:1304 Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (RecognitionManager.js:219)
    at eval (RecognitionManager.js:290)
    at eval (RecognitionManager.js:385)
    at Object.../node_modules/react-speech-recognition/lib/RecognitionManager.js (app.js:793)
    at __webpack_require__ (app.js:1301)
    at fn (app.js:1512)
    at eval (SpeechRecognition.js:16)
    at Object.../node_modules/react-speech-recognition/lib/SpeechRecognition.js (app.js:804)
    at __webpack_require__ (app.js:1301)
    at fn (app.js:1512)

**Comment by mariuszbeltowski** [comment]
Same here

**Comment by prescottbreeden** [comment]
I am getting this error running jest but browser is running fine

**Comment by naveenbasyal** [comment]
> 

Thankyou so much , it works fine now !!

**Comment by Robertishimwe** [comment]
> Hi @rafaelsouzagomes @mariuszbeltowski have you tried [this](https://github.com/JamesBrill/react-speech-recognition#regeneratorruntime-is-not-defined)?

this did not work

**Comment by Mizan-Rifat** [comment]
> Hi @rafaelsouzagomes @mariuszbeltowski have you tried [this](https://github.com/JamesBrill/react-speech-recognition#regeneratorruntime-is-not-defined)?

Not working for me

**Comment by priyanshusaini105** [comment]
> I am getting this error running jest but browser is running fine, is fixed by adding `import 'regenerator-runtime'` at the top of files importing `SpeechRecognition`

Still not working

**Comment by Osama3576** [comment]
> Hi @LeXuanNguyen @amirzenoozi Check out [this](https://github.com/JamesBrill/react-speech-recognition#regeneratorruntime-is-not-defined). Let me know if that helps.

Yes this works thanks a lot.

**Comment by jsandlerus** [comment]
FYI! You need to include the `import 'regenerator-runtime/runtime'
` at the top of the page.tsx file/s where you are using the library. In my case, it was at the top of the page.tsx of a nested tree. It did not work for me when I added it at the top of the root layout or at the root page.tsx. I'm using NextJS 13 App Dir
![tree](https://github.com/JamesBrill/react-speech-recognition/assets/46496940/fe64db07-f532-4d46-b541-dd23563c0ba8)

**Comment by anuragd-dataslush** [comment]
> import 'regenerator-runtime/runtime'

in my case i've already installed and importing regenerator-runtime, but still i can see regeneratorRuntime is not defined in every browsers  including Chrome.

**Comment by aadij7** [comment]
Can anyone let me know the reason behind the error, and what additions including this library to our environment is doing?

**Comment by Mizan-Rifat** [comment]
`import "regenerator-runtime/runtime";`
 
installing `regenerator-runtime` and adding this line at the top of the file solved my issue.
Remember to add the import statement at the very first line of your file

**Comment by ManishaSwain8** [comment]
If you are using React make sure to add this  [ import "regenerator-runtime/runtime"; ] at line 1 of  " main.jsx" file
OR
If using Javascript add the above import statement at line 1 of  " index.js" file

**Comment by toluolatubosun** [comment]
> I am getting this error running jest but browser is running fine, is fixed by adding `import 'regenerator-runtime'` at the top of files importing `SpeechRecognition`

This solved it for me
