### ISSUE TITLE
It is not working in windows 10 Home version 21H2

### ISSUE THREAD

**Issue by MohammedAliBinTaleb** [JamesBrill/react-speech-recognition#133]
I use this package in my pc as windows pro version 21H1
and it is works fine but
when I format my laptop and update in windows 10  21H2 and  use this library for recording it is not working 
When i start recording voice it shut immediately after open recording rather than wait for user to add his voice

I hope @JamesBrill   If you can solve this problem as soon as possible 🙏 

Thanks for great package🌹

**Comment by JamesBrill** [comment]
Hi @MohammedAliBinTaleb Which browser are you using?

It would be unusual for the version of the operating system to affect how this library performs. One thing I've seen in the past is Windows "forgetting" microphone devices when being updated, which can prevent browsers from consuming voice data. It might be worth checking that Windows still knows about your microphone devices - you may need to re-register them in your system settings.

What happens if you try [this Web Speech demo](https://mdn.github.io/web-speech-api/speech-color-changer/)? If it works for you, then we can eliminate the missing microphone theory.

If it's not the microphone, perhaps you can share any error output in the console (if any).

**Comment by MohammedAliBinTaleb** [comment]
Hi @JamesBrill 
the problem has been solve when i  switch browser from Edge to Chrome
even Firefox give me same error but when i use Chrome It is work fine👍

**Comment by JamesBrill** [comment]
Ah yes, the Web Speech API is [only supported in a few browsers](https://github.com/JamesBrill/react-speech-recognition#supported-browsers). Surprised it doesn't work in Edge though - it used to a couple of years ago.

If you need voice support to work in all browsers, I recommend looking into a [polyfill](https://github.com/JamesBrill/react-speech-recognition#why-you-should-use-a-polyfill-with-this-library).

**Comment by MohammedAliBinTaleb** [comment]
yeah microsoft edge work when i use in my pc however 
it didn't work when i use my laptop so instead of using edge i use chrome and it works 👌

**Comment by Criztiandev** [comment]
Mine is Error occurred in recognition: network but my internet is fast ? Im using Edge
