### ISSUE TITLE
Chrome on iOS not working

### ISSUE THREAD

**Issue by waelmas** [JamesBrill/react-speech-recognition#80]
It seems like speech recognition is not working on Chrome on iOS devices.

Not sure I'm doing something wrong but it seems like the fallback is triggered as if the browser did not support speech recognition at all.

```
  	useEffect(() => {
		if (!SpeechRecognition.browserSupportsSpeechRecognition()) {
            return (() => {
                SpeechRecognition.stopListening();
                resetTranscript();
            })
	  	}
  		if(microPhoneOn) {
              SpeechRecognition.startListening({continuous: true, language: "en"})
  		}
  		else {
            SpeechRecognition.stopListening();	
  		}
		if(props.onTranscriptReceived) {
            props.onTranscriptReceived(messages);
		}  		
  		return (() => {
              SpeechRecognition.stopListening();
              resetTranscript();
  		})
      }, [microPhoneOn, prevMessage]);
```

**Comment by JamesBrill** [comment]
Hi @waelmas It seems that the Web Speech API is not supported by iOS on any browser. So `SpeechRecognition.browserSupportsSpeechRecognition()` will return `false` on that platform. I will update the README to state this. There is a project to enable an AWS-based polyfill for the Web Speech API to enable it to work on unsupported browsers - you can follow its progress [here](https://github.com/JamesBrill/react-speech-recognition/discussions/79). 

Also, I recommend looking at the [examples](https://github.com/JamesBrill/react-speech-recognition/tree/master/example/src/Dictaphone) to see how you can consume this library. For `browserSupportsSpeechRecognition`, the [pattern](https://github.com/JamesBrill/react-speech-recognition/blob/master/example/src/Dictaphone/Dictaphone.js#L25) I'd recommend is to use it to render fallback content (or null), rather than using it in an effect hook.
